api_key: fiusnBLmOLANDuFPMSzidkQdG8HYeK3YNgwPy4uiNgTshfiaNyGxQXCyJB2OwYQTxscOLTh8ke6FSD0iSeE8eV95YUZF70oOc+jHxh12ypSh07aYq66Zm/B4h0nB62UEli87g0FaG4oh5jUvZZmXFn4H+2qeoPsgVSQo0+/xIog=
device_id: '84040000850001'
