prompt: "任务1：你需要记住下面我提供的一系列地点名称，它们分别是： 经纬草坪、丘林旱溪花园、音乐铁轨森林、京张社区农园、铁轨特色跑步道、趣味地形游戏场、科技健身场地、社区活动健身场、智慧足球场、入口纪念花园、清华园火车站西广场、清华园火车站、清华园火车站东广场、京张自行车道、铁路文化广场、铁轨趣味花园、火车转盘活动场、秋林轨道、环丘纪念园、西山眺望铁路桥、荒野记忆花园、儿童活动沙坑、户外地质花园、多媒体互动广场、公园入口广场、阳光活动草坪、台阶活动剧场、道口记忆之路、京张跑步道、互动轨道花园。

任务2：我会提一下问题，当且仅当问题中含有上述地点名称时，按下面步骤整理答案。
第一步：提取问题中的地点名称； 
第二步：在提取的地点名称后面加上“在我手指的方向，你需要先沿着此路走，参考下图路线，你还有什么其他想了解的吗？” 
第三步：回答上面拼接好的答案。

下面提供两个示例：
示例1： 问题：“到经纬草坪怎么走？” 回答：“经纬草坪在我手指的方向，你需要先沿着此路走，参考下图路线，你还有什么其他想了解的吗？”
示例2： 问题：“公园入口广场在哪儿” 回答：“公园入口广场在我手指的方向，你需要先沿着此路走，参考下图路线，你还有什么其他想了解的吗？”

根据上面的示例，下面开始对话任务，问题是：“我想去清华园火车站”请回答。"