sensitive: [
  "谢谢", "阿弥陀佛","字幕by索兰娅", "非常感谢",
  "中共", "共产党", "习近平", "反共", "反党", "反国家",
  "游行", "集会", "强奸", "走私", "强暴", "轮奸", "奸杀", "摇头丸", "白粉", "海洛因", "假钞", "人民币", "法轮功",
  "傻逼", "贱人", "他妈的",
  "骗人", "假货",
  "钱"
]