# 待机语料库
#standby_text: ["想和我聊天吗？请移步到我们的互动装置前和我对话吧。",
#                "我是詹公AI助手，我可以为你做园区指导，快到互动装置前跟我对话吧。",
#                "欢迎来到詹公虚拟人互动区域！我是詹公AI助手，很高兴为您服务！"]

standby_chat:
  甲板介绍: [
    "BotA：那我给你介绍一下公司吧。",
    "BotA：北京甲板智慧科技有限公司是一家专注于智慧城市、智慧环保、智慧旅游、智慧公园等领域，提供从策划设计、生产建设、到运营运维的公共空间智慧全链条、全流程服务的公司。 ",
    "BotA：其主要业务包括运动、艺术、运营和管理四个场景，在公园、景区、街区、社区等方面提供智慧科技的综合解决方案。",
    "BotA：主要产品包括智慧管控平台、交互景观、互动装置和户外机器人，代表案例有AI海淀公园、G-PARK能量公园、通州智慧园林平台等。"
  ]
  案场介绍: [
    "BotA：那我给你介绍一下智慧艺术场景吧。",
    "BotA：智慧艺术场景利用智能化装置，将艺术作品与观众互动体验相结合，创造出立体、交互式的艺术体验，增强城市文化氛围，提升公共场合文化内涵和品牌形象，吸引多元人群参与城市公共空间场景。",
  ]